
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.touhou.mystiasizakaya.init;

import net.touhou.mystiasizakaya.item.ZunYuItem;
import net.touhou.mystiasizakaya.item.ZhuZiItem;
import net.touhou.mystiasizakaya.item.ZhuTongZhengDanItem;
import net.touhou.mystiasizakaya.item.ZhuSunItem;
import net.touhou.mystiasizakaya.item.ZhuSunChaoRouItem;
import net.touhou.mystiasizakaya.item.ZhuRouZunYuXunItem;
import net.touhou.mystiasizakaya.item.ZhuRouItem;
import net.touhou.mystiasizakaya.item.ZhuRouGaiJiaoFanItem;
import net.touhou.mystiasizakaya.item.ZhuQuJiItem;
import net.touhou.mystiasizakaya.item.ZhuLuDieItem;
import net.touhou.mystiasizakaya.item.kitchenwares.ZhuGuoItem;
import net.touhou.mystiasizakaya.item.ZhuDouFuItem;
import net.touhou.mystiasizakaya.item.ZhiZhuRouFanTuanItem;
import net.touhou.mystiasizakaya.item.ZhiShiItem;
import net.touhou.mystiasizakaya.item.kitchenwares.ZhengGuoItem;
import net.touhou.mystiasizakaya.item.ZhenHaiXianWeiChengTangItem;
import net.touhou.mystiasizakaya.item.ZhangYuItem;
import net.touhou.mystiasizakaya.item.ZhaZhuRouPaiItem;
import net.touhou.mystiasizakaya.item.ZhaBaMuManItem;
import net.touhou.mystiasizakaya.item.ZaChuiItem;
import net.touhou.mystiasizakaya.item.YueZhiLianRenItem;
import net.touhou.mystiasizakaya.item.YueMianHuoJianItem;
import net.touhou.mystiasizakaya.item.YueGuangTuanZiItem;
import net.touhou.mystiasizakaya.item.YueGuangCaoItem;
import net.touhou.mystiasizakaya.item.beverages.YuLuChaItem;
import net.touhou.mystiasizakaya.item.kitchenwares.YouGuoItem;
import net.touhou.mystiasizakaya.item.YouDouFuItem;
import net.touhou.mystiasizakaya.item.YingLuoXueItem;
import net.touhou.mystiasizakaya.item.YiShiHuiFanItem;
import net.touhou.mystiasizakaya.item.YeZhuRouItem;
import net.touhou.mystiasizakaya.item.YeWeiJiaNongItem;
import net.touhou.mystiasizakaya.item.beverages.YaoJingYuLuItem;
import net.touhou.mystiasizakaya.item.beverages.YangZhiGanLuItem;
import net.touhou.mystiasizakaya.item.YangCongItem;
import net.touhou.mystiasizakaya.item.YanJiangItem;
import net.touhou.mystiasizakaya.item.beverages.XingHongEMoItem;
import net.touhou.mystiasizakaya.item.XingHongEMoDanGaoItem;
import net.touhou.mystiasizakaya.item.beverages.XiaoItem;
import net.touhou.mystiasizakaya.item.XiangZhaChanShuiItem;
import net.touhou.mystiasizakaya.item.XiangJianSanWenYuItem;
import net.touhou.mystiasizakaya.item.XiaItem;
import net.touhou.mystiasizakaya.item.WuYiShiYaoGuaiMuSiItem;
import net.touhou.mystiasizakaya.item.WenNuanFanTuanItem;
import net.touhou.mystiasizakaya.item.TunGuLaMianItem;
import net.touhou.mystiasizakaya.item.TuDouKeLeBingItem;
import net.touhou.mystiasizakaya.item.TuDouItem;
import net.touhou.mystiasizakaya.item.beverages.TianGouYongItem;
import net.touhou.mystiasizakaya.item.TaoZiItem;
import net.touhou.mystiasizakaya.item.TaoHuaGengItem;
import net.touhou.mystiasizakaya.item.TangYuanItem;
import net.touhou.mystiasizakaya.item.SongZiItem;
import net.touhou.mystiasizakaya.item.SongLuItem;
import net.touhou.mystiasizakaya.item.SiKangBingItem;
import net.touhou.mystiasizakaya.item.ShuiZhuYuItem;
import net.touhou.mystiasizakaya.item.beverages.ShuiTaJiItem;
import net.touhou.mystiasizakaya.item.ShuiJiaoItem;
import net.touhou.mystiasizakaya.item.ShuCaiZhuanJiItem;
import net.touhou.mystiasizakaya.item.ShiSiYeItem;
import net.touhou.mystiasizakaya.item.ShiLiYinXingItem;
import net.touhou.mystiasizakaya.item.ShenZhiMaiItem;
import net.touhou.mystiasizakaya.item.kitchenwares.ShaoKaoJiaItem;
import net.touhou.mystiasizakaya.item.ingredients.SanWenYuItem;
import net.touhou.mystiasizakaya.item.SaiXiongZhangItem;
import net.touhou.mystiasizakaya.item.beverages.RiYueXingItem;
import net.touhou.mystiasizakaya.item.ReSongBingItem;
import net.touhou.mystiasizakaya.item.beverages.QueJiuItem;
import net.touhou.mystiasizakaya.item.beverages.QiLinItem;
import net.touhou.mystiasizakaya.item.beverages.QiItem;
import net.touhou.mystiasizakaya.item.beverages.QiBaoJianItem;
import net.touhou.mystiasizakaya.item.beverages.PuTongJianShenChaItem;
import net.touhou.mystiasizakaya.item.PuTaoItem;
import net.touhou.mystiasizakaya.item.PengLaiYuZhiItem;
import net.touhou.mystiasizakaya.item.PangXieItem;
import net.touhou.mystiasizakaya.item.NuoMiItem;
import net.touhou.mystiasizakaya.item.NiuRouItem;
import net.touhou.mystiasizakaya.item.NiuRouGaiJiaoFanItem;
import net.touhou.mystiasizakaya.item.beverages.NiuNaiItem;
import net.touhou.mystiasizakaya.item.ingredients.NingMengItem;
import net.touhou.mystiasizakaya.item.NiGeLuoNiItem;
import net.touhou.mystiasizakaya.item.NengLiangChuanItem;
import net.touhou.mystiasizakaya.item.NanGuaItem;
import net.touhou.mystiasizakaya.item.NaiYouTunCaiItem;
import net.touhou.mystiasizakaya.item.NaiYouItem;
import net.touhou.mystiasizakaya.item.MoGuRouPianItem;
import net.touhou.mystiasizakaya.item.MoGuItem;
import net.touhou.mystiasizakaya.item.MianFenItem;
import net.touhou.mystiasizakaya.item.MiZhiXiaoYuGanItem;
import net.touhou.mystiasizakaya.item.MiZhiChaShaoItem;
import net.touhou.mystiasizakaya.item.beverages.MeiJiuItem;
import net.touhou.mystiasizakaya.item.MaoYuSanSeBingJiLingItem;
import net.touhou.mystiasizakaya.item.MaoYuRongYanDouFuItem;
import net.touhou.mystiasizakaya.item.MaShuItem;
import net.touhou.mystiasizakaya.item.MaPoDouFuItem;
import net.touhou.mystiasizakaya.item.LuoBuItem;
import net.touhou.mystiasizakaya.item.LuShuiZhuDanItem;
import net.touhou.mystiasizakaya.item.LuShuiItem;
import net.touhou.mystiasizakaya.item.LuRouItem;
import net.touhou.mystiasizakaya.item.beverages.LuChaItem;
import net.touhou.mystiasizakaya.item.LiuShuiSuMianItem;
import net.touhou.mystiasizakaya.item.utils.LingXianItem;
import net.touhou.mystiasizakaya.item.kitchenwares.LiaoLiTaiItem;
import net.touhou.mystiasizakaya.item.LiangCaiDiaoHuaItem;
import net.touhou.mystiasizakaya.item.LianZiItem;
import net.touhou.mystiasizakaya.item.LiLiangTangItem;
import net.touhou.mystiasizakaya.item.LengDouFuItem;
import net.touhou.mystiasizakaya.item.LaJiaoItem;
import net.touhou.mystiasizakaya.item.KaoMoGuItem;
import net.touhou.mystiasizakaya.item.KaoBaMuManItem;
import net.touhou.mystiasizakaya.item.beverages.KaPeiItem;
import net.touhou.mystiasizakaya.item.JinQiangYuItem;
import net.touhou.mystiasizakaya.item.beverages.JiaoFuItem;
import net.touhou.mystiasizakaya.item.JiShangJinQiangYuItem;
import net.touhou.mystiasizakaya.item.JiDanItem;
import net.touhou.mystiasizakaya.item.utils.IronKnifeItem;
import net.touhou.mystiasizakaya.item.utils.IconItem;
import net.touhou.mystiasizakaya.item.HuoShuQiuItem;
import net.touhou.mystiasizakaya.item.HuiLingDunNiuPaiItem;
import net.touhou.mystiasizakaya.item.HuangYouNiuPaiItem;
import net.touhou.mystiasizakaya.item.HuangYouItem;
import net.touhou.mystiasizakaya.item.HuangGuaItem;
import net.touhou.mystiasizakaya.item.HuanTanHuaItem;
import net.touhou.mystiasizakaya.item.HuanTanHuaGaoItem;
import net.touhou.mystiasizakaya.item.HuaGuangYuJianBaoItem;
import net.touhou.mystiasizakaya.item.HongYouGuoZhiItem;
import net.touhou.mystiasizakaya.item.beverages.HongWuItem;
import net.touhou.mystiasizakaya.item.HongShaoManYuItem;
import net.touhou.mystiasizakaya.item.HongMoGuanHongChaItem;
import net.touhou.mystiasizakaya.item.HeiYanItem;
import net.touhou.mystiasizakaya.item.HeiMaoZhuRouItem;
import net.touhou.mystiasizakaya.item.HeiAnWuZhiItem;
import net.touhou.mystiasizakaya.item.HeTunItem;
import net.touhou.mystiasizakaya.item.HeNiuItem;
import net.touhou.mystiasizakaya.item.HaiXianWeiChengTangItem;
import net.touhou.mystiasizakaya.item.HaiTaiItem;
import net.touhou.mystiasizakaya.item.HaiDanItem;
import net.touhou.mystiasizakaya.item.beverages.GuoWeiSOURItem;
import net.touhou.mystiasizakaya.item.beverages.GuoWeiHighBallItem;
import net.touhou.mystiasizakaya.item.beverages.GuiShaItem;
import net.touhou.mystiasizakaya.item.GuMingDiBingJiLingItem;
import net.touhou.mystiasizakaya.item.beverages.GuFaNaiYouBingShaItem;
import net.touhou.mystiasizakaya.item.beverages.FengZhuItem;
import net.touhou.mystiasizakaya.item.FengMiItem;
import net.touhou.mystiasizakaya.item.FanTuanItem;
import net.touhou.mystiasizakaya.item.ErTianLiuItem;
import net.touhou.mystiasizakaya.item.currency.En5Item;
import net.touhou.mystiasizakaya.item.currency.En1Item;
import net.touhou.mystiasizakaya.item.currency.En10kItem;
import net.touhou.mystiasizakaya.item.currency.En10Item;
import net.touhou.mystiasizakaya.item.DouFuWeiChengItem;
import net.touhou.mystiasizakaya.item.DouFuItem;
import net.touhou.mystiasizakaya.item.DouFuGuoItem;
import net.touhou.mystiasizakaya.item.beverages.DongNiangItem;
import net.touhou.mystiasizakaya.item.DiGuaItem;
import net.touhou.mystiasizakaya.item.beverages.DaYinNiangItem;
import net.touhou.mystiasizakaya.item.DaSheYanItem;
import net.touhou.mystiasizakaya.item.beverages.DaBingGunErItem;
import net.touhou.mystiasizakaya.item.DaBanShaoItem;
import net.touhou.mystiasizakaya.item.CiShenPinPanItem;
import net.touhou.mystiasizakaya.item.ChouDouFuItem;
import net.touhou.mystiasizakaya.item.beverages.ChaoZUNPiJiuItem;
import net.touhou.mystiasizakaya.item.ChaoRouSiItem;
import net.touhou.mystiasizakaya.item.ChanShuiItem;
import net.touhou.mystiasizakaya.item.BuSiNiaoItem;
import net.touhou.mystiasizakaya.item.beverages.BoZiQiShuiItem;
import net.touhou.mystiasizakaya.item.BingShanMaoYuDongNingItem;
import net.touhou.mystiasizakaya.item.BingKuaiItem;
import net.touhou.mystiasizakaya.item.BingDiLianItem;
import net.touhou.mystiasizakaya.item.BeiJiTianXiaMiTaoSeLaItem;
import net.touhou.mystiasizakaya.item.BanNiDiKeDanItem;
import net.touhou.mystiasizakaya.item.BanLiItem;
import net.touhou.mystiasizakaya.item.beverages.BaiXueItem;
import net.touhou.mystiasizakaya.item.BaiTaoShengBaQiaoItem;
import net.touhou.mystiasizakaya.item.BaiGuoLuoBuPaiGuTangItem;
import net.touhou.mystiasizakaya.item.BaiGuoItem;
import net.touhou.mystiasizakaya.item.BaMuManItem;
import net.touhou.mystiasizakaya.item.beverages.AFuJiaDuoItem;
import net.touhou.mystiasizakaya.MystiasIzakayaMod;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

public class MystiasIzakayaModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, MystiasIzakayaMod.MODID);
	public static final RegistryObject<Item> COOKING_RANGE = block(MystiasIzakayaModBlocks.COOKING_RANGE);
	public static final RegistryObject<Item> BANK = block(MystiasIzakayaModBlocks.BANK);
	public static final RegistryObject<Item> LIAO_LI_TAI = REGISTRY.register("liao_li_tai", () -> new LiaoLiTaiItem());
	public static final RegistryObject<Item> SHAO_KAO_JIA = REGISTRY.register("shao_kao_jia", () -> new ShaoKaoJiaItem());
	public static final RegistryObject<Item> YOU_GUO = REGISTRY.register("you_guo", () -> new YouGuoItem());
	public static final RegistryObject<Item> ZHENG_GUO = REGISTRY.register("zheng_guo", () -> new ZhengGuoItem());
	public static final RegistryObject<Item> ZHU_GUO = REGISTRY.register("zhu_guo", () -> new ZhuGuoItem());
	public static final RegistryObject<Item> BA_MU_MAN = REGISTRY.register("ba_mu_man", () -> new BaMuManItem());
	public static final RegistryObject<Item> BAI_GUO = REGISTRY.register("bai_guo", () -> new BaiGuoItem());
	public static final RegistryObject<Item> BAN_LI = REGISTRY.register("ban_li", () -> new BanLiItem());
	public static final RegistryObject<Item> BING_KUAI = REGISTRY.register("bing_kuai", () -> new BingKuaiItem());
	public static final RegistryObject<Item> BING_DI_LIAN = REGISTRY.register("bing_di_lian", () -> new BingDiLianItem());
	public static final RegistryObject<Item> CHAN_SHUI = REGISTRY.register("chan_shui", () -> new ChanShuiItem());
	public static final RegistryObject<Item> DI_GUA = REGISTRY.register("di_gua", () -> new DiGuaItem());
	public static final RegistryObject<Item> DOU_FU = REGISTRY.register("dou_fu", () -> new DouFuItem());
	public static final RegistryObject<Item> FENG_MI = REGISTRY.register("feng_mi", () -> new FengMiItem());
	public static final RegistryObject<Item> HAI_DAN = REGISTRY.register("hai_dan", () -> new HaiDanItem());
	public static final RegistryObject<Item> HAI_TAI = REGISTRY.register("hai_tai", () -> new HaiTaiItem());
	public static final RegistryObject<Item> HE_NIU = REGISTRY.register("he_niu", () -> new HeNiuItem());
	public static final RegistryObject<Item> HE_TUN = REGISTRY.register("he_tun", () -> new HeTunItem());
	public static final RegistryObject<Item> HEI_MAO_ZHU_ROU = REGISTRY.register("hei_mao_zhu_rou", () -> new HeiMaoZhuRouItem());
	public static final RegistryObject<Item> HEI_YAN = REGISTRY.register("hei_yan", () -> new HeiYanItem());
	public static final RegistryObject<Item> HUAN_TAN_HUA = REGISTRY.register("huan_tan_hua", () -> new HuanTanHuaItem());
	public static final RegistryObject<Item> HUANG_GUA = REGISTRY.register("huang_gua", () -> new HuangGuaItem());
	public static final RegistryObject<Item> HUANG_YOU = REGISTRY.register("huang_you", () -> new HuangYouItem());
	public static final RegistryObject<Item> JI_DAN = REGISTRY.register("ji_dan", () -> new JiDanItem());
	public static final RegistryObject<Item> JI_SHANG_JIN_QIANG_YU = REGISTRY.register("ji_shang_jin_qiang_yu", () -> new JiShangJinQiangYuItem());
	public static final RegistryObject<Item> JIN_QIANG_YU = REGISTRY.register("jin_qiang_yu", () -> new JinQiangYuItem());
	public static final RegistryObject<Item> LA_JIAO = REGISTRY.register("la_jiao", () -> new LaJiaoItem());
	public static final RegistryObject<Item> LIAN_ZI = REGISTRY.register("lian_zi", () -> new LianZiItem());
	public static final RegistryObject<Item> LU_ROU = REGISTRY.register("lu_rou", () -> new LuRouItem());
	public static final RegistryObject<Item> LU_SHUI = REGISTRY.register("lu_shui", () -> new LuShuiItem());
	public static final RegistryObject<Item> LUO_BU = REGISTRY.register("luo_bu", () -> new LuoBuItem());
	public static final RegistryObject<Item> MIAN_FEN = REGISTRY.register("mian_fen", () -> new MianFenItem());
	public static final RegistryObject<Item> MO_GU = REGISTRY.register("mo_gu", () -> new MoGuItem());
	public static final RegistryObject<Item> NAI_YOU = REGISTRY.register("nai_you", () -> new NaiYouItem());
	public static final RegistryObject<Item> NAN_GUA = REGISTRY.register("nan_gua", () -> new NanGuaItem());
	public static final RegistryObject<Item> NING_MENG = REGISTRY.register("ning_meng", () -> new NingMengItem());
	public static final RegistryObject<Item> NIU_ROU = REGISTRY.register("niu_rou", () -> new NiuRouItem());
	public static final RegistryObject<Item> NUO_MI = REGISTRY.register("nuo_mi", () -> new NuoMiItem());
	public static final RegistryObject<Item> PANG_XIE = REGISTRY.register("pang_xie", () -> new PangXieItem());
	public static final RegistryObject<Item> PU_TAO = REGISTRY.register("pu_tao", () -> new PuTaoItem());
	public static final RegistryObject<Item> SAN_WEN_YU = REGISTRY.register("san_wen_yu", () -> new SanWenYuItem());
	public static final RegistryObject<Item> SONG_LU = REGISTRY.register("song_lu", () -> new SongLuItem());
	public static final RegistryObject<Item> SONG_ZI = REGISTRY.register("song_zi", () -> new SongZiItem());
	public static final RegistryObject<Item> TAO_ZI = REGISTRY.register("tao_zi", () -> new TaoZiItem());
	public static final RegistryObject<Item> TU_DOU = REGISTRY.register("tu_dou", () -> new TuDouItem());
	public static final RegistryObject<Item> XIA = REGISTRY.register("xia", () -> new XiaItem());
	public static final RegistryObject<Item> YANG_CONG = REGISTRY.register("yang_cong", () -> new YangCongItem());
	public static final RegistryObject<Item> YE_ZHU_ROU = REGISTRY.register("ye_zhu_rou", () -> new YeZhuRouItem());
	public static final RegistryObject<Item> YUE_GUANG_CAO = REGISTRY.register("yue_guang_cao", () -> new YueGuangCaoItem());
	public static final RegistryObject<Item> ZHANG_YU = REGISTRY.register("zhang_yu", () -> new ZhangYuItem());
	public static final RegistryObject<Item> ZHI_SHI = REGISTRY.register("zhi_shi", () -> new ZhiShiItem());
	public static final RegistryObject<Item> ZHU_ROU = REGISTRY.register("zhu_rou", () -> new ZhuRouItem());
	public static final RegistryObject<Item> ZHU_SUN = REGISTRY.register("zhu_sun", () -> new ZhuSunItem());
	public static final RegistryObject<Item> ZHU_ZI = REGISTRY.register("zhu_zi", () -> new ZhuZiItem());
	public static final RegistryObject<Item> ZUN_YU = REGISTRY.register("zun_yu", () -> new ZunYuItem());
	public static final RegistryObject<Item> BAI_GUO_LUO_BU_PAI_GU_TANG = REGISTRY.register("bai_guo_luo_bu_pai_gu_tang", () -> new BaiGuoLuoBuPaiGuTangItem());
	public static final RegistryObject<Item> BAI_TAO_SHENG_BA_QIAO = REGISTRY.register("bai_tao_sheng_ba_qiao", () -> new BaiTaoShengBaQiaoItem());
	public static final RegistryObject<Item> BAI_XUE = REGISTRY.register("bai_xue", () -> new BaiXueItem());
	public static final RegistryObject<Item> BAN_NI_DI_KE_DAN = REGISTRY.register("ban_ni_di_ke_dan", () -> new BanNiDiKeDanItem());
	public static final RegistryObject<Item> BEI_JI_TIAN_XIA_MI_TAO_SE_LA = REGISTRY.register("bei_ji_tian_xia_mi_tao_se_la", () -> new BeiJiTianXiaMiTaoSeLaItem());
	public static final RegistryObject<Item> BU_SI_NIAO = REGISTRY.register("bu_si_niao", () -> new BuSiNiaoItem());
	public static final RegistryObject<Item> CHAO_ROU_SI = REGISTRY.register("chao_rou_si", () -> new ChaoRouSiItem());
	public static final RegistryObject<Item> CHOU_DOU_FU = REGISTRY.register("chou_dou_fu", () -> new ChouDouFuItem());
	public static final RegistryObject<Item> CI_SHEN_PIN_PAN = REGISTRY.register("ci_shen_pin_pan", () -> new CiShenPinPanItem());
	public static final RegistryObject<Item> DA_BAN_SHAO = REGISTRY.register("da_ban_shao", () -> new DaBanShaoItem());
	public static final RegistryObject<Item> DA_SHE_YAN = REGISTRY.register("da_she_yan", () -> new DaSheYanItem());
	public static final RegistryObject<Item> DOU_FU_GUO = REGISTRY.register("dou_fu_guo", () -> new DouFuGuoItem());
	public static final RegistryObject<Item> DOU_FU_WEI_CHENG = REGISTRY.register("dou_fu_wei_cheng", () -> new DouFuWeiChengItem());
	public static final RegistryObject<Item> ER_TIAN_LIU = REGISTRY.register("er_tian_liu", () -> new ErTianLiuItem());
	public static final RegistryObject<Item> FAN_TUAN = REGISTRY.register("fan_tuan", () -> new FanTuanItem());
	public static final RegistryObject<Item> HAI_XIAN_WEI_CHENG_TANG = REGISTRY.register("hai_xian_wei_cheng_tang", () -> new HaiXianWeiChengTangItem());
	public static final RegistryObject<Item> HONG_SHAO_MAN_YU = REGISTRY.register("hong_shao_man_yu", () -> new HongShaoManYuItem());
	public static final RegistryObject<Item> HUA_GUANG_YU_JIAN_BAO = REGISTRY.register("hua_guang_yu_jian_bao", () -> new HuaGuangYuJianBaoItem());
	public static final RegistryObject<Item> HUAN_TAN_HUA_GAO = REGISTRY.register("huan_tan_hua_gao", () -> new HuanTanHuaGaoItem());
	public static final RegistryObject<Item> HUANG_YOU_NIU_PAI = REGISTRY.register("huang_you_niu_pai", () -> new HuangYouNiuPaiItem());
	public static final RegistryObject<Item> HUI_LING_DUN_NIU_PAI = REGISTRY.register("hui_ling_dun_niu_pai", () -> new HuiLingDunNiuPaiItem());
	public static final RegistryObject<Item> KAO_BA_MU_MAN = REGISTRY.register("kao_ba_mu_man", () -> new KaoBaMuManItem());
	public static final RegistryObject<Item> KAO_MO_GU = REGISTRY.register("kao_mo_gu", () -> new KaoMoGuItem());
	public static final RegistryObject<Item> LENG_DOU_FU = REGISTRY.register("leng_dou_fu", () -> new LengDouFuItem());
	public static final RegistryObject<Item> LI_LIANG_TANG = REGISTRY.register("li_liang_tang", () -> new LiLiangTangItem());
	public static final RegistryObject<Item> LIANG_CAI_DIAO_HUA = REGISTRY.register("liang_cai_diao_hua", () -> new LiangCaiDiaoHuaItem());
	public static final RegistryObject<Item> LIU_SHUI_SU_MIAN = REGISTRY.register("liu_shui_su_mian", () -> new LiuShuiSuMianItem());
	public static final RegistryObject<Item> LU_SHUI_ZHU_DAN = REGISTRY.register("lu_shui_zhu_dan", () -> new LuShuiZhuDanItem());
	public static final RegistryObject<Item> MA_PO_DOU_FU = REGISTRY.register("ma_po_dou_fu", () -> new MaPoDouFuItem());
	public static final RegistryObject<Item> MA_SHU = REGISTRY.register("ma_shu", () -> new MaShuItem());
	public static final RegistryObject<Item> MAO_YU_RONG_YAN_DOU_FU = REGISTRY.register("mao_yu_rong_yan_dou_fu", () -> new MaoYuRongYanDouFuItem());
	public static final RegistryObject<Item> MAO_YU_SAN_SE_BING_JI_LING = REGISTRY.register("mao_yu_san_se_bing_ji_ling", () -> new MaoYuSanSeBingJiLingItem());
	public static final RegistryObject<Item> MI_ZHI_XIAO_YU_GAN = REGISTRY.register("mi_zhi_xiao_yu_gan", () -> new MiZhiXiaoYuGanItem());
	public static final RegistryObject<Item> MI_ZHI_CHA_SHAO = REGISTRY.register("mi_zhi_cha_shao", () -> new MiZhiChaShaoItem());
	public static final RegistryObject<Item> MO_GU_ROU_PIAN = REGISTRY.register("mo_gu_rou_pian", () -> new MoGuRouPianItem());
	public static final RegistryObject<Item> NAI_YOU_TUN_CAI = REGISTRY.register("nai_you_tun_cai", () -> new NaiYouTunCaiItem());
	public static final RegistryObject<Item> NENG_LIANG_CHUAN = REGISTRY.register("neng_liang_chuan", () -> new NengLiangChuanItem());
	public static final RegistryObject<Item> NIU_ROU_GAI_JIAO_FAN = REGISTRY.register("niu_rou_gai_jiao_fan", () -> new NiuRouGaiJiaoFanItem());
	public static final RegistryObject<Item> PENG_LAI_YU_ZHI = REGISTRY.register("peng_lai_yu_zhi", () -> new PengLaiYuZhiItem());
	public static final RegistryObject<Item> RE_SONG_BING = REGISTRY.register("re_song_bing", () -> new ReSongBingItem());
	public static final RegistryObject<Item> SAI_XIONG_ZHANG = REGISTRY.register("sai_xiong_zhang", () -> new SaiXiongZhangItem());
	public static final RegistryObject<Item> SHI_LI_YIN_XING = REGISTRY.register("shi_li_yin_xing", () -> new ShiLiYinXingItem());
	public static final RegistryObject<Item> SHU_CAI_ZHUAN_JI = REGISTRY.register("shu_cai_zhuan_ji", () -> new ShuCaiZhuanJiItem());
	public static final RegistryObject<Item> SHUI_JIAO = REGISTRY.register("shui_jiao", () -> new ShuiJiaoItem());
	public static final RegistryObject<Item> SHUI_ZHU_YU = REGISTRY.register("shui_zhu_yu", () -> new ShuiZhuYuItem());
	public static final RegistryObject<Item> SI_KANG_BING = REGISTRY.register("si_kang_bing", () -> new SiKangBingItem());
	public static final RegistryObject<Item> TANG_YUAN = REGISTRY.register("tang_yuan", () -> new TangYuanItem());
	public static final RegistryObject<Item> TAO_HUA_GENG = REGISTRY.register("tao_hua_geng", () -> new TaoHuaGengItem());
	public static final RegistryObject<Item> TU_DOU_KE_LE_BING = REGISTRY.register("tu_dou_ke_le_bing", () -> new TuDouKeLeBingItem());
	public static final RegistryObject<Item> TUN_GU_LA_MIAN = REGISTRY.register("tun_gu_la_mian", () -> new TunGuLaMianItem());
	public static final RegistryObject<Item> WEN_NUAN_FAN_TUAN = REGISTRY.register("wen_nuan_fan_tuan", () -> new WenNuanFanTuanItem());
	public static final RegistryObject<Item> WU_YI_SHI_YAO_GUAI_MU_SI = REGISTRY.register("wu_yi_shi_yao_guai_mu_si", () -> new WuYiShiYaoGuaiMuSiItem());
	public static final RegistryObject<Item> XIANG_JIAN_SAN_WEN_YU = REGISTRY.register("xiang_jian_san_wen_yu", () -> new XiangJianSanWenYuItem());
	public static final RegistryObject<Item> XIANG_ZHA_CHAN_SHUI = REGISTRY.register("xiang_zha_chan_shui", () -> new XiangZhaChanShuiItem());
	public static final RegistryObject<Item> XING_HONG_E_MO_DAN_GAO = REGISTRY.register("xing_hong_e_mo_dan_gao", () -> new XingHongEMoDanGaoItem());
	public static final RegistryObject<Item> YAN_JIANG = REGISTRY.register("yan_jiang", () -> new YanJiangItem());
	public static final RegistryObject<Item> YE_WEI_JIA_NONG = REGISTRY.register("ye_wei_jia_nong", () -> new YeWeiJiaNongItem());
	public static final RegistryObject<Item> YI_SHI_HUI_FAN = REGISTRY.register("yi_shi_hui_fan", () -> new YiShiHuiFanItem());
	public static final RegistryObject<Item> YING_LUO_XUE = REGISTRY.register("ying_luo_xue", () -> new YingLuoXueItem());
	public static final RegistryObject<Item> YOU_DOU_FU = REGISTRY.register("you_dou_fu", () -> new YouDouFuItem());
	public static final RegistryObject<Item> YUE_GUANG_TUAN_ZI = REGISTRY.register("yue_guang_tuan_zi", () -> new YueGuangTuanZiItem());
	public static final RegistryObject<Item> YUE_ZHI_LIAN_REN = REGISTRY.register("yue_zhi_lian_ren", () -> new YueZhiLianRenItem());
	public static final RegistryObject<Item> ZA_CHUI = REGISTRY.register("za_chui", () -> new ZaChuiItem());
	public static final RegistryObject<Item> ZHA_BA_MU_MAN = REGISTRY.register("zha_ba_mu_man", () -> new ZhaBaMuManItem());
	public static final RegistryObject<Item> ZHA_ZHU_ROU_PAI = REGISTRY.register("zha_zhu_rou_pai", () -> new ZhaZhuRouPaiItem());
	public static final RegistryObject<Item> ZHEN_HAI_XIAN_WEI_CHENG_TANG = REGISTRY.register("zhen_hai_xian_wei_cheng_tang", () -> new ZhenHaiXianWeiChengTangItem());
	public static final RegistryObject<Item> ZHI_ZHU_ROU_FAN_TUAN = REGISTRY.register("zhi_zhu_rou_fan_tuan", () -> new ZhiZhuRouFanTuanItem());
	public static final RegistryObject<Item> ZHU_LU_DIE = REGISTRY.register("zhu_lu_die", () -> new ZhuLuDieItem());
	public static final RegistryObject<Item> ZHU_ROU_GAI_JIAO_FAN = REGISTRY.register("zhu_rou_gai_jiao_fan", () -> new ZhuRouGaiJiaoFanItem());
	public static final RegistryObject<Item> ZHU_ROU_ZUN_YU_XUN = REGISTRY.register("zhu_rou_zun_yu_xun", () -> new ZhuRouZunYuXunItem());
	public static final RegistryObject<Item> ZHU_QU_JI = REGISTRY.register("zhu_qu_ji", () -> new ZhuQuJiItem());
	public static final RegistryObject<Item> ZHU_SUN_CHAO_ROU = REGISTRY.register("zhu_sun_chao_rou", () -> new ZhuSunChaoRouItem());
	public static final RegistryObject<Item> ZHU_TONG_ZHENG_DAN = REGISTRY.register("zhu_tong_zheng_dan", () -> new ZhuTongZhengDanItem());
	public static final RegistryObject<Item> ZHU_DOU_FU = REGISTRY.register("zhu_dou_fu", () -> new ZhuDouFuItem());
	public static final RegistryObject<Item> HEI_AN_WU_ZHI = REGISTRY.register("hei_an_wu_zhi", () -> new HeiAnWuZhiItem());
	public static final RegistryObject<Item> LU_CHA = REGISTRY.register("lu_cha", () -> new LuChaItem());
	public static final RegistryObject<Item> SHUI_TA_JI = REGISTRY.register("shui_ta_ji", () -> new ShuiTaJiItem());
	public static final RegistryObject<Item> QUE_JIU = REGISTRY.register("que_jiu", () -> new QueJiuItem());
	public static final RegistryObject<Item> GUO_WEI_HIGH_BALL = REGISTRY.register("guo_wei_high_ball", () -> new GuoWeiHighBallItem());
	public static final RegistryObject<Item> GUO_WEI_SOUR = REGISTRY.register("guo_wei_sour", () -> new GuoWeiSOURItem());
	public static final RegistryObject<Item> QI = REGISTRY.register("qi", () -> new QiItem());
	public static final RegistryObject<Item> MEI_JIU = REGISTRY.register("mei_jiu", () -> new MeiJiuItem());
	public static final RegistryObject<Item> CHAO_ZUN_PI_JIU = REGISTRY.register("chao_zun_pi_jiu", () -> new ChaoZUNPiJiuItem());
	public static final RegistryObject<Item> RI_YUE_XING = REGISTRY.register("ri_yue_xing", () -> new RiYueXingItem());
	public static final RegistryObject<Item> NIU_NAI = REGISTRY.register("niu_nai", () -> new NiuNaiItem());
	public static final RegistryObject<Item> HONG_YOU_GUO_ZHI = REGISTRY.register("hong_you_guo_zhi", () -> new HongYouGuoZhiItem());
	public static final RegistryObject<Item> BO_ZI_QI_SHUI = REGISTRY.register("bo_zi_qi_shui", () -> new BoZiQiShuiItem());
	public static final RegistryObject<Item> FENG_ZHU = REGISTRY.register("feng_zhu", () -> new FengZhuItem());
	public static final RegistryObject<Item> TIAN_GOU_YONG = REGISTRY.register("tian_gou_yong", () -> new TianGouYongItem());
	public static final RegistryObject<Item> SHEN_ZHI_MAI = REGISTRY.register("shen_zhi_mai", () -> new ShenZhiMaiItem());
	public static final RegistryObject<Item> XING_HONG_E_MO = REGISTRY.register("xing_hong_e_mo", () -> new XingHongEMoItem());
	public static final RegistryObject<Item> XIAO = REGISTRY.register("xiao", () -> new XiaoItem());
	public static final RegistryObject<Item> A_FU_JIA_DUO = REGISTRY.register("a_fu_jia_duo", () -> new AFuJiaDuoItem());
	public static final RegistryObject<Item> HONG_MO_GUAN_HONG_CHA = REGISTRY.register("hong_mo_guan_hong_cha", () -> new HongMoGuanHongChaItem());
	public static final RegistryObject<Item> HONG_WU = REGISTRY.register("hong_wu", () -> new HongWuItem());
	public static final RegistryObject<Item> NI_GE_LUO_NI = REGISTRY.register("ni_ge_luo_ni", () -> new NiGeLuoNiItem());
	public static final RegistryObject<Item> JIAO_FU = REGISTRY.register("jiao_fu", () -> new JiaoFuItem());
	public static final RegistryObject<Item> YUE_MIAN_HUO_JIAN = REGISTRY.register("yue_mian_huo_jian", () -> new YueMianHuoJianItem());
	public static final RegistryObject<Item> SHI_SI_YE = REGISTRY.register("shi_si_ye", () -> new ShiSiYeItem());
	public static final RegistryObject<Item> DONG_NIANG = REGISTRY.register("dong_niang", () -> new DongNiangItem());
	public static final RegistryObject<Item> YU_LU_CHA = REGISTRY.register("yu_lu_cha", () -> new YuLuChaItem());
	public static final RegistryObject<Item> HUO_SHU_QIU = REGISTRY.register("huo_shu_qiu", () -> new HuoShuQiuItem());
	public static final RegistryObject<Item> BING_SHAN_MAO_YU_DONG_NING = REGISTRY.register("bing_shan_mao_yu_dong_ning", () -> new BingShanMaoYuDongNingItem());
	public static final RegistryObject<Item> DA_BING_GUN_ER = REGISTRY.register("da_bing_gun_er", () -> new DaBingGunErItem());
	public static final RegistryObject<Item> DA_YIN_NIANG = REGISTRY.register("da_yin_niang", () -> new DaYinNiangItem());
	public static final RegistryObject<Item> KA_PEI = REGISTRY.register("ka_pei", () -> new KaPeiItem());
	public static final RegistryObject<Item> GU_FA_NAI_YOU_BING_SHA = REGISTRY.register("gu_fa_nai_you_bing_sha", () -> new GuFaNaiYouBingShaItem());
	public static final RegistryObject<Item> YAO_JING_YU_LU = REGISTRY.register("yao_jing_yu_lu", () -> new YaoJingYuLuItem());
	public static final RegistryObject<Item> PU_TONG_JIAN_SHEN_CHA = REGISTRY.register("pu_tong_jian_shen_cha", () -> new PuTongJianShenChaItem());
	public static final RegistryObject<Item> GUI_SHA = REGISTRY.register("gui_sha", () -> new GuiShaItem());
	public static final RegistryObject<Item> QI_BAO_JIAN = REGISTRY.register("qi_bao_jian", () -> new QiBaoJianItem());
	public static final RegistryObject<Item> GU_MING_DI_BING_JI_LING = REGISTRY.register("gu_ming_di_bing_ji_ling", () -> new GuMingDiBingJiLingItem());
	public static final RegistryObject<Item> YANG_ZHI_GAN_LU = REGISTRY.register("yang_zhi_gan_lu", () -> new YangZhiGanLuItem());
	public static final RegistryObject<Item> QI_LIN = REGISTRY.register("qi_lin", () -> new QiLinItem());
	public static final RegistryObject<Item> REISEN = REGISTRY.register("reisen", () -> new LingXianItem());
	public static final RegistryObject<Item> EN_1 = REGISTRY.register("en_1", () -> new En1Item());
	public static final RegistryObject<Item> EN_5 = REGISTRY.register("en_5", () -> new En5Item());
	public static final RegistryObject<Item> EN_10 = REGISTRY.register("en_10", () -> new En10Item());
	public static final RegistryObject<Item> ICON = REGISTRY.register("icon", () -> new IconItem());
	public static final RegistryObject<Item> EN_10K = REGISTRY.register("en_10k", () -> new En10kItem());
	public static final RegistryObject<Item> IRON_KNIFE = REGISTRY.register("iron_knife", () -> new IronKnifeItem());

	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}
}
