modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://www.curseforge.com/minecraft/mc-mods/mystias-izakaya"
credits="modding from 东方夜雀食堂"
authors="${mod_authors}"
description=""

[[dependencies."${mod_id}"]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"



[[dependencies."${mod_id}"]]
modId="jei"
mandatory=false
versionRange="[0,)"
ordering="NONE"
side="BOTH"

